#!/usr/bin/env bash
# ============================================================
# setup_local_airflow.sh
# Run once from the airflow/ directory to initialise your
# local .env with generated secrets.
# Usage: bash setup_local_airflow.sh
# ============================================================
set +e
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "⚠️  .env already exists at $ENV_FILE — skipping to avoid overwriting secrets."
  echo "   Delete it first if you want to regenerate."
  exit 0
fi

echo "🔐 Generating Airflow secrets..."

FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ADMIN_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")
AIRFLOW_UID=$(id -u)

echo "📋 Please provide your AWS credentials for youtube-pipeline-admin:"
read -rp "  AWS_ACCESS_KEY_ID: "     AWS_ACCESS_KEY_ID
read -rsp "  AWS_SECRET_ACCESS_KEY: " AWS_SECRET_ACCESS_KEY
echo ""

# Detect dbt project path
DBT_PROJECT_DEFAULT="/Volumes/Crucial 500GB/youtube_analytics_pipeline/dbt"
DBT_PROFILES_DEFAULT="${HOME}/.dbt"

read -rp "  dbt project path [${DBT_PROJECT_DEFAULT}]: " DBT_PROJECT
DBT_PROJECT="${DBT_PROJECT:-$DBT_PROJECT_DEFAULT}"

read -rp "  dbt profiles dir [${DBT_PROFILES_DEFAULT}]: " DBT_PROFILES
DBT_PROFILES="${DBT_PROFILES:-$DBT_PROFILES_DEFAULT}"

cat > "$ENV_FILE" << EOF
# Generated by setup_local_airflow.sh — DO NOT COMMIT
AIRFLOW_FERNET_KEY=${FERNET_KEY}
AIRFLOW_SECRET_KEY=${SECRET_KEY}
AIRFLOW_ADMIN_PASSWORD=${ADMIN_PASSWORD}

AWS_DEFAULT_REGION=us-east-1
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

YOUTUBE_BRONZE_BUCKET=youtube-raw-dev-900932787422
YOUTUBE_GLUE_DB=youtube_analytics_dev
YOUTUBE_DBT_PROJECT_DIR=${DBT_PROJECT}
YOUTUBE_DBT_PROFILES_DIR=${DBT_PROFILES}

AIRFLOW_UID=${AIRFLOW_UID}
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✅ .env written to $ENV_FILE"
echo ""
echo "🔑 Admin password: ${ADMIN_PASSWORD}"
echo "   (also saved in .env)"
echo ""
echo "Next steps:"
echo "  1. cd airflow/"
echo "  2. docker compose up airflow-init   # first-time DB setup"
echo "  3. docker compose up -d             # start all services"
echo "  4. Open http://localhost:8080"
echo "  5. Add AWS connection in UI:"
echo "     Admin → Connections → aws_default"
echo "     Type: Amazon Web Services"
echo "     (credentials are already in env vars, so leave key/secret blank)"